version: '3'

services:
###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: app
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: root
#       POSTGRES_USER: app
#     healthcheck:
#       test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
#       timeout: 5s
#       retries: 5
#       start_period: 60s
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###
  database: 
      image: mysql:8.0.32
      environment: 
          # - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=app
          - MYSQL_ROOT_PASSWORD=root
      ports: 
          - "${MYSQL_PORT:-3306}:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
